### ISSUE TITLE
Task scheduler behavior

### ISSUE THREAD

**Issue by lucasjose501** [Blobbackup/Blobbackup#102]
Noticed that even setting the backup to Manual the interface will open hourly based on the task scheduler, even if I close the program.
Not sure if this is the designed behavior, but if I set it to manual, shouldn't the task also be removed and avoid the program opening itself hourly?

This is thinking about user experience. If I close and exit it in the taskbar, I want it closed, period.
I think that the correct would be to it start with windows and run the backup automatically if the user allows it, but if the software is closed, it should not open again.

Checkbox "Start BlobBackup on Windows start up" (or Mac, Linux, etc) should be an option and then the scheduler hourly, or every n hours to run the backup task.

**Comment by bimbashrestha** [comment]
Hey @lucasjose501, thanks for the issue. 

In one of the newer versions, I added the option `--open-minimized` which gets passed by default to the windows task. So now you shouldn't get the intrusive window popping up every hour or so. 

Perhaps you already discovered this but there are actually two schedulers in play. Blobbackup uses the native OS's scheduler (Task Scheduler on Windows and LaunchAgents on Macs) to ensure that Blobbackup is always running. It does this by opening the application every hour (if it isn't already open). This is what you were seeing with the annoying popups. And Blobbackup uses another scheduler (that only works when the application is running) to trigger the actual backups. 

>Checkbox "Start BlobBackup on Windows start up" (or Mac, Linux, etc) should be an option and then the scheduler hourly, or every n hours to run the backup task.

We could certainly add more advanced options to the in-app scheduler (eg: every X hours, at a specific time, etc). Some of those are already in the original Blobbackup app.

**Comment by lucasjose501** [comment]
I got it fixed, the thing was I was running it on another folder because I'm compiling it locally but the schedule task created was targeting the one in Program Files folder (Hard coded on client side). Fixed it moving my compiled version to the intended location. Window is not popping anymore.
