### ISSUE TITLE
Versioning?

### ISSUE THREAD

**Issue by estiens** [Blobbackup/Blobbackup#136]
I know it's not the lightest lift, but wondering if there is an idea to save different versions of files (up to X changes back) and/or allow multiple snapshots (say monthly/weekly/current)

**Comment by bimbashrestha** [comment]
Hey @estiens thanks for posting an issue.

Perhaps I misunderstand (let me know if i did) but Blobbackup already stores all past hourly snapshots. You can see them by:
1. Opening the restore dialog by clicking on "Restore files" from the control panel or menu bar menu.
2. Clicking the the little dropdown arrow next to the current snapshot timestamp.

**Comment by bimbashrestha** [comment]
@estiens so if you click this dropdown:
<img width="568" alt="Screen Shot 2022-05-05 at 6 02 15 PM" src="https://user-images.githubusercontent.com/14875426/167041162-95d3aacf-dae4-412f-a785-a766946313e0.png">

you'll see a list of all your past snapshots (which you can choose from) like this: 
<img width="524" alt="Screen Shot 2022-05-05 at 6 02 24 PM" src="https://user-images.githubusercontent.com/14875426/167041202-a1bd63de-6f63-4e03-b625-5148364a8e4f.png">
