### ISSUE TITLE
Finder tags and file creation/modification date not preserved in macOS

### ISSUE THREAD

**Issue by nullpointerninja** [BlobBackup/BlobBackup#42]
I tested a backup and restore operation with a Local Directory target on macOS 11.2.2.
The restored files don't keep the file creation and modification dates, and any finder tags (colors) are lost. Is this expected, or is it a bug?
This was tested with a simple text file with different creation and modification dates, with a couple of Finder tags. I can provide more information and/or screenshots if needed.

**Comment by bimbashrestha** [comment]
@nullpointerninja thanks for asking and welcome the project! 

>The restored files don't keep the file creation and modification dates, and any finder tags (colors) are lost. Is this expected, or is it a bug?

The only metadata that is preserved is file modified time at the moment. So yes this is expected. It's not ideal but the initial data format doesn't have support for other metadata.

**Comment by bimbashrestha** [comment]
Hey @nullpointerninja I just re-read your post. Didn't realize that you weren't seeing modified time on the restored files. Can you confirm this is so? Because that part is unexpected. Modified times should be backed up and restored.

**Comment by nullpointerninja** [comment]
Yes, the file modification and creation times as seen from the Finder file info dialog show the restore time instead of the original modify date. This is true for both files and folders that are restores. Just tested with v1.0.0.beta2.

**Comment by bimbashrestha** [comment]
Ahh okay. This makes sense. Im going to close this issue for now but feel free to add comments. 

I'd like to eventually add support for other metadata like extended attributes on osx but that'll require a data format upgrade which I'd like to hold off on for a little while.

**Comment by bimbashrestha** [comment]
Hmm strange. I'll look into this soon

**Comment by bimbashrestha** [comment]
Ah actually this makes sense. You are testing using one of the pre packaged releases. Two weeks ago I merged a PR that preserves restore time and that hasn't made it to a release yet. 

Perhaps you could give the dev branch a try with pip? The instructions are on the main README. Thanks

**Comment by nullpointerninja** [comment]
Tried to install with pip but got many errors and couldn't find the root cause :(.
Will try the next packaged release and report back. Would be nice to have creation dates and finder tags supported in the future though.
Thanks!

**Comment by bimbashrestha** [comment]
Sounds good! Thanks for testing.
