### ISSUE TITLE
[Feture Request] Change Backup Name and add memo

### ISSUE THREAD

**Issue by kuyagic** [BlobBackup/BlobBackup#49]
How Can I Change the backup name ,and is it possible to add some memo to existing backup set
Thank you

**Comment by bimbashrestha** [comment]
Hi! Thanks for the issue. This is currently not possible but I think we should add it since it's such a common use case. 

It's on the backlog:)

**Comment by bimbashrestha** [comment]
Hi @kuyagic just added a new field to allow backup name changes btw! If you could try it out, that'd be great! 

I'm going to skip adding the memo for now. I'd like to keep things as simple as possible and I feel like most people can compensate for the lack of a memo with slightly more descriptive backup names. What do you think?
