### ISSUE TITLE
404 link on documentation

### ISSUE THREAD

**Issue by marius00** [BlobBackup/BlobBackup#50]
![image](https://user-images.githubusercontent.com/5671213/119228131-d2c69580-bb11-11eb-8f64-95b78415b2cb.png)

This takes you to https://blobbackup.com/docs.php which returns 404 not found

**Comment by bimbashrestha** [comment]
Hey thanks for reporting. I believe this has been fixed in the dev version:) so I'll go ahead and close it. Feel free to leave more comments.
