### ISSUE TITLE
Any interest or suggestion on data parity?

### ISSUE THREAD

**Issue by cmpute** [BlobBackup/BlobBackup#59]
I'm searching for a backup tool with recovery record support (like in RAR). This is not critical in cloud storage, but very useful for storage offline in external hard drive or other media. Currently the only solution I found for incremental back up with recovery record support is [DAR](http://dar.linux.free.fr/) with the help of PAR2, which is kind of overkill for daily files backup, and it's not designed for cloud storage.

Do you think it's a good idea to integrate parity in BlobBackup? It's both good for offline storage, and also fixing file error during internet transmission. If not, I wonder is there any other backup tool supporting data parity?

**Comment by bimbashrestha** [comment]
Hey, thanks for posting an issue!

I'm not sure I completely understand how it could be implemented into a solution like BlobBackup. Did you have a specific approach in mind?

**Comment by cmpute** [comment]
After I tried BlobBackup, I found the backup consists of small files... So I don't have any idea in mind actually. But thanks for your reply!

**Comment by bimbashrestha** [comment]
I don't see a short term action item for this topic so I'm going to close it for now. 

Thanks for bringing it up still. Feel free to leave more comments below!
