### ISSUE TITLE
BlobBackup keeps desktop files open - Cannot edit or delete

### ISSUE THREAD

**Issue by pri11er** [Blobbackup/Blobbackup#64]
**Issue:**  After BlobBackup backs up a file on Windows Desktop, that file cannot be edited/saved or deleted.  When attempting to delete the file, Windows gives an error that "The action can't be completed because the file is open in BlobBackup".   When editing a file and attempting to save it, the error is "The process cannot access the file because it is being used by another process".

Note that BlobBackup has completed a successful backup and is idle.  The file can only be release by exiting BlobBackup.  This appears to only happen with files on the Desktop.  Files in the Documents folder, etc. are fine.

**Steps to Reproduce:** 
- Create a new text file and save it on Windows Desktop. 
- Run a backup that includes the desktop. 
- Then try to drag the file into the Recycle Bin - It will fail with the above noted error.
- Edit the file and attempt to save it -  It will fail with the above noted error.
- Exit BlobBackup and you will be able to successfully perform the above tasks.

**Environment**
Windows 10 Home
BlobBackup  v1.0.0.beta2

**Comment by bimbashrestha** [comment]
Hey. Thanks for reporting! I think I know what the issue might be. I'll have a look soon.

**Comment by bimbashrestha** [comment]
Hey @pri11er sorry for the delay in getting back to this. I just fixed a bug that was causing the last file backed up to remain open even after a backup operation finished. This has never been a problem for me but I normally use either mac or linux so perhaps it's something that only surfaces on windows. Either way, it should be fixed now on the dev branch. Do you mind giving it a try when you have a chance?

Let me know if you need instructions for building the dev branch!

**Comment by bimbashrestha** [comment]
Bug fixed
