### ISSUE TITLE
Silent install

### ISSUE THREAD

**Issue by laedit** [Blobbackup/Blobbackup#66]
Is it possible to install BlobBackup silently?
I haven't found if the installer generated by pyinstaller supports it.
The goal is to be able to install it from a script, unattended.

**Comment by bimbashrestha** [comment]
Hmm does downloading the binary from the releases using something like curl count as a silent install?

**Comment by laedit** [comment]
That can be a workaround but it would miss the start menu shortcut and probably other things added by the installer.
But I understand if it is too complicated.

**Comment by laedit** [comment]
Well, InstallForge doesn't handle silent install [for now](https://installforge.net/support1/docs/running-your-setup-package-in-silent-mode/).

**Comment by bimbashrestha** [comment]
Ah I think it might be too much of a hassle then. I'm going to close this for now
