### ISSUE TITLE
Export/import settings

### ISSUE THREAD

**Issue by laedit** [BlobBackup/BlobBackup#67]
Is it possible/planned to export/import backups settings?
In any case thanks a lot for this software, I was looking for these exact features for some time.

**Comment by bimbashrestha** [comment]
I can see that being useful. It might be a bit tricky since the backup settings are encrypted. 

One thing you could try is to simply copy/paste the backup folder .blobbackup in the home directory.

**Comment by laedit** [comment]
Thanks, will try that!

**Comment by laedit** [comment]
It seems to work well, thanks!

**Comment by bimbashrestha** [comment]
Awesome. I think most people will find that solution good enough. I'm going to close this issue for now. Feel free to leave more comments or reopen.

**Comment by laedit** [comment]
Well after copying the .blobbackup folder on a fresh install on windows it seems that the settings aren't recognized :'(

**Comment by laedit** [comment]
Is the encryption based on the machine?  
Could it be based on a user-known password like rclone configuration encryption?
