### ISSUE TITLE
Forbid some chars in prefix for cloud backends

### ISSUE THREAD

**Issue by laedit** [BlobBackup/BlobBackup#70]
I use the [object storage](https://www.scaleway.com/en/object-storage/) from Scaleway which is s3 compatible but I keep getting the following error when trying to add it as a new source:
![image](https://user-images.githubusercontent.com/871092/142568873-e1a713da-69c3-4f86-8b1e-a27ce16f3ada.png)

I have tested the parameters used to connect with [AWS CLI](https://aws.amazon.com/cli/) and [Minio Client](https://docs.min.io/docs/minio-client-quickstart-guide) and both works well.

Did I do something wrong?
I didn't find any log to have more details on the error.

**Comment by laedit** [comment]
After some more tests with boto3, it appears that the issue was from my prefix which was ending with a `-`.
So maybe it's worth forbidding some chars in the prefix?

**Comment by bimbashrestha** [comment]
Thanks for posting this issue and for digging into boto3!

I think this touches on a slightly larger issue. When there is a connection error like this one on any backend, we don't surface a user friendly error. We just tell them that the connection failed (which is pretty unfriendly). We might be able to just start by surfacing the exception type in that pop up error and make it more user friendly as time goes on.

**Comment by bimbashrestha** [comment]
HI @laedit, I just merged a PR that surfaces the exception type. I suspect the boto3 exception thrown will be surfaced now. Do you mind trying to connect to your path ending in `-` and see if a more friendly error message is shown whenever you have time. Thanks!

**Comment by laedit** [comment]
Well now it works ><
![image](https://user-images.githubusercontent.com/871092/142994445-76f3120d-ed5e-4975-9c00-c60510e55da9.png)
![image](https://user-images.githubusercontent.com/871092/142994637-e18141f9-2347-4fa0-b366-1833ff27c8b6.png)
But I think that the title should include the name of the backup and not only the path/prefix.

**Comment by bimbashrestha** [comment]
Closing this for now. Feel free to leave more comments underneath!

**Comment by laedit** [comment]
After a fresh install of windows and therefore of blobbackup it is impossible to add an S3 backup.  
I think that it can be caused by an older version of boto3 that can be fixed with a new release of blobbackup since I didn't have the issue with the development version.
