### ISSUE TITLE
Improve error message when a scheduled backup runs on an unplugged source

### ISSUE THREAD

**Issue by laedit** [BlobBackup/BlobBackup#71]
When a scheduled backup runs on a source based on an unplugged external hard drive, the following message appears:
![image](https://user-images.githubusercontent.com/871092/142750657-c355d741-c604-4998-9a49-722b215aafaf.png)
Nothing big, but it would be awesome to have only a message indicating that the source is missing.

**Comment by bimbashrestha** [comment]
Hey @laedit thanks so much for these issues you've created! I really appreciate it. 

My plan is to find some time over the coming US holidays to look through them! Cheers

**Comment by laedit** [comment]
Thanks! No pressure, BlobBackup is already very great right now :)

**Comment by bimbashrestha** [comment]
Related to https://github.com/BlobBackup/BlobBackup/pull/76
